syntax keyword jsNew new
syntax keyword jsTypeOf typeof
syntax keyword jsDelete delete
syntax keyword jsInstaceOf instanceof
syntax keyword jsVoid void
syntax keyword jsIn in
syntax keyword jsOf of
syntax cluster jsExpression add=jsNew
syntax cluster jsExpression add=jsTypeOf
syntax cluster jsExpression add=jsDelete
syntax cluster jsExpression add=jsInstanceOf
syntax cluster jsExpression add=jsVoid
syntax cluster jsExpression add=jsIn
syntax cluster jsExpression add=jsOf
