"syntax match OperatorChars "?\|+\|-\|\*\|;\|:\|,\|<\|>\|&\||\|!\|\~\|%\|=\|)\|(\|{\|}\|\.\|\[\|\]\|/\(/\|*\)\@!"
" syntax match OperatorChars "+\|-\|\*\|<\|>\|&\||\|!\|\~\|%\|=\|/\(/\|*\)\@!"
syntax match OperatorChars "+\|-\|\*\|<\|>\|&\||\|!\|\~\|%\|=\|@!"
syntax match rubyRailsRootUrl "root_url"
syntax match rubyRailsControllerMethod "require"
